### PR TITLE
please add color option of the highlight

### PR DESCRIPTION
**Pull request by pluieciel**
I need to extract highlight based on different colors, (e.g: green highlight is positive, red highlight is negtive).
I tried to find the Color info as 'C':[1,1,0] (RGB) and add it in the Annotation Class as a.color, but I am not skillful to add that to input/output part.
Please add color info if you think that is useful, thanks a lot!

### CODE REVIEW

**Comment by 0xabu** [comment]
Hmm, I don't see myself using this … although I'm not sure what you want to do with the colour. It sounds like you want to group the highlights based on the colour that was used, and then output them one colour-group at a time? Or did you just want to print the "colour" information in some way when you emit the highlight?

**Comment by pluieciel** [comment]
Hi @0xabu , thanks a lot for your code first!
The reason is that I need to group the highlights based on colors. I have searched for a while to find color information.
I could modify the code to meet my own need, but I think it might help others if they also want to find color information of the highlights or group by colors.

**Comment by 0xabu** [comment]
It's not obvious to me how you would output that though … printing the numeric RGB values in the output is clearly not useful, so something needs to map those colour values back to named colours or categories, and that mapping probably needs to be user-configurable somehow.

Also, selfishly, this is a feature I don't see myself making use of :) So, thanks for the suggestion, but I think for now this is something you'll want to hack up for your own use. If you do get something working that you think might be of wider value feel free to reopen this PR.

**Comment by pluieciel** [comment]
I agree. RGB values could be hard to input as categories.
Thanks again for your work!

**Pull request closed without merging**
