### PR TITLE
feat: add logseq output format (md + edn files)

### PR DESCRIPTION
**Pull request by thiswillbeyourgithub**
Hi,
I needed a way to import my already annotated pdf into logseq and ended up forking your project to create this.

I decided to make the PR to get some feedback.

I hope you don't mind!

- new: add boxes information to json format
- feat: support edn output for logseq

edit : it seems the coordinate system of logseq and pdfannots differ. If you have any idea let me know!

### CODE REVIEW

**Comment by thiswillbeyourgithub** [comment]
I decided to move my code to a specific repo, thanks a lot for the inspiration!

**Comment by 0xabu** [comment]
Hey, sorry for the slow reply. I'm happy to review contributions to the core of pdfannots if they'd make your project easier, e.g. recording and exporting highlight colors which is a feature others have asked for.

**Comment by 0xabu** [comment]
I don't know what logseq is, but pdfminer uses PDF page coordinates: origin 0,0 is the bottom left of the page, and the units are 1/72 in.

**Comment by thiswillbeyourgithub** [comment]
Thanks. By any chance do you know how I could find the other possible coordinate specification ?

**Pull request closed without merging**
