### PR TITLE
Update pdfannots.py

### PR DESCRIPTION
**Pull request by bfelder**
Major overhaul of code.
- Annotations are now exported to pdf with filename: original_name.sum.pdf.
- New pdf are automatically endowed with first page of source pdf as cover.
- Usage: pdfannots.py --outdir=targetdirectory file1.pdf file2.pdf ... (multiple file args possible).
- Progress is displayed via tqdm.
- Cleanup and rectification of old code.
- Extraction from multiple files is sped up via multiprocessing.

### CODE REVIEW

**Comment by 0xabu** [comment]
Hi,

Thanks for the contribution, and sorry for the slow response. As I indicated in email, I don't think it makes sense to merge this functionality. What you've added feels to me like it should be a separate tool -- it's solving a different problem from the one I intended, and it adds a lot of extra dependencies to the tool. If you want to build upon the core of pdfannots I'd be open to less invasive changes that refactor some of the internals, if that helps achieve what you want.

Cheers,
Andrew

**Comment by bfelder** [comment]
You are right in not merging. It would have made sense only if I accidentally developed what you mght have secretly wished pdfannots to become one day.
I will publish my own interpretation of pdfannots under a new repository name that more accurately reflects its purpose. **I'll hope you do not mind this?** Of course, you will get an honorable mention as the original author.

**Comment by 0xabu** [comment]
As long as you comply with the license, you're free to fork and republish as you wish.

**Comment by bfelder** [comment]
Thanks. Of course, I comply with the license. Especially if it contains a big name like Microsoft. :) I was asking out of respect. Thanks again for the good cooperation, Andrew.

**Pull request closed without merging**
