### PR TITLE
GUI - Graphical User Interface (Tkinter)

### PR DESCRIPTION
**Pull request by IgorAvilaPereira**
I liked of your project. This project was important for my work. Because this, I developed a GUI with Tkinter. 
For run: python main.py 
Sorry my english. I am from Brazil.  I expect that you like my improvements.
Thanks.
My Setup: Linux Mint 21 and Python 3.10

### CODE REVIEW

**Comment by tgraupne** [comment]
Hi @0xabu , hi @IgorAvilaPereira ,

I just wanted to bring to your attention that I started working on an UI for pdfannots:
https://github.com/tgraupne/pdfannots-app

Currently, I am struggling to create a working executable and really integrate pdfannots as a library instead of using the system call. I would really appreciate if you could get in touch and share some of your knowledge.

I think this library is really amazing and I am trying to make it more popular at my local university. Having a complete application which would work ootb on multiple platforms would be just terrific.

Best, Tom

**Comment by IgorAvilaPereira** [comment]
@tgraupne I am happy by your job.
I also tried to implement a GUI user interface to pdfannots with Tkinter.  Here, I just invoke a system call. 
https://github.com/IgorAvilaPereira/pdfannots
This works for me but I agree with you that would be important to the project these improvements.
Thank you for your mention.

**Comment by another4til7** [comment]
I'm not a python programmer. BUT, I would love to help with testing and feedback when you've got something that can be tested on either (Ubuntu) Linux or Windows.

**Comment by tgraupne** [comment]
> @tgraupne I am happy by your job.
> I also tried to implement a GUI user interface to pdfannots with Tkinter. Here, I just invoke a system call.
> https://github.com/IgorAvilaPereira/pdfannots
> This works for me but I agree with you that would be important to the project these improvements.
> Thank you for your mention.

Actually, this PR and your work with Tkinker inspired me. I played around with Tkinter too for a while. But when I was researching possibilities to implement something which could work cross-platform, I stumbled across [flet.dev](https://flet.dev). A framework based on flutter which is promising to enable easy and quick cross-platform applications.

What would you think about me writing up an issue in my project describing the most pressing issue I have? So we could all take a look and continue our discussion over there.

**Comment by IgorAvilaPereira** [comment]
@tgraupne The invitation has expired. Can you send again?

**Comment by IgorAvilaPereira** [comment]
@tgraupne Today I implemented a function that don't need command line invocation (main_igor) in:

https://github.com/IgorAvilaPereira/pdfannots-tkinter-app/blob/master/pdfannots/cli.py

Thanks

**Pull request closed without merging**
